<!DOCTYPE html> <html lang="en"> <head> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"> <meta charset="utf-8"> <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <title>Error and Exception in Python | Duc Minh Quang Nguyen</title> <meta name="author" content="Duc Minh Quang Nguyen"> <meta name="description" content="# A simple, whitespace theme for academics. Based on [*folio](https://github.com/bogoli/-folio) design. "> <meta name="keywords" content="jekyll, jekyll-theme, academic-website, portfolio-website"> <link rel="stylesheet" href="/assets/css/bootstrap.min.css?a4b3f509e79c54a512b890d73235ef04"> <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/mdbootstrap@4.20.0/css/mdb.min.css" integrity="sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw=" crossorigin="anonymous"> <link defer rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.22.1/dist/bootstrap-table.min.css"> <link rel="stylesheet" href="/assets/css/academicons.min.css?f0b7046b84e425c55f3463ac249818f5"> <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:100,300,400,500,700|Material+Icons"> <link rel="stylesheet" href="/assets/css/jekyll-pygments-themes-github.css?19f3075a2d19613090fe9e16b564e1fe" media="" id="highlight_theme_light"> <link rel="stylesheet" href="/assets/css/main.css?d41d8cd98f00b204e9800998ecf8427e"> <link rel="canonical" href="https://nminhquang380.github.io/myblog/2023/error_exception_python/"> <link rel="stylesheet" href="/assets/css/jekyll-pygments-themes-native.css?e74e74bf055e5729d44a7d031a5ca6a5" media="none" id="highlight_theme_dark"> <script src="/assets/js/theme.js?96d6b3e1c3604aca8b6134c7afdd5db6"></script> <script src="/assets/js/dark_mode.js?9b17307bb950ffa2e34be0227f53558f"></script> </head> <body class="fixed-top-nav "> <header> <nav id="navbar" class="navbar navbar-light navbar-expand-sm fixed-top"> <div class="container"> <a class="navbar-brand title font-weight-lighter" href="/"><span class="font-weight-bold">Duc Minh Quang </span>Nguyen</a> <button class="navbar-toggler collapsed ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar top-bar"></span> <span class="icon-bar middle-bar"></span> <span class="icon-bar bottom-bar"></span> </button> <div class="collapse navbar-collapse text-right" id="navbarNav"> <ul class="navbar-nav ml-auto flex-nowrap"> <li class="nav-item "> <a class="nav-link" href="/">About</a> </li> <li class="nav-item active"> <a class="nav-link" href="/blog/">Blog<span class="sr-only">(current)</span></a> </li> <li class="nav-item "> <a class="nav-link" href="/repositories/">Portfolio</a> </li> <li class="nav-item "> <a class="nav-link" href="/cv/">Resume</a> </li> <li class="nav-item "> <a class="nav-link" href="/bucket_list/">My Bucket List</a> </li> <li class="toggle-container"> <button id="light-toggle" title="Change theme"> <i class="fa-solid fa-moon"></i> <i class="fa-solid fa-sun"></i> </button> </li> </ul> </div> </div> </nav> <progress id="progress" value="0"> <div class="progress-container"> <span class="progress-bar"></span> </div> </progress> </header> <div class="container mt-5"> <div class="post"> <header class="post-header"> <h1 class="post-title">Error and Exception in Python</h1> <p class="post-meta">August 31, 2023</p> <p class="post-tags"> <i class="fa-solid fa-calendar fa-sm"></i> 2023   ·   <i class="fa-solid fa-tag fa-sm"></i> machinelearning   </p> </header> <article class="post-content"> <div id="markdown-content"> <p>As one of the dullest fools among software developers club, I was aware of Exceptions recently though I have writen many Exception codelines in some languages. It sounds impossible, right?</p> <p>Yeah, I agree. But if you know my story, it would be understandable.</p> <p>Ha! Sorry, it’s not story-telling time, come to our topic: <strong>Errors and Exceptions</strong>.</p> <p>I found an easy and simple tutorial in this <a href="https://docs.python.org/3/tutorial/errors.html#user-defined-exceptions" rel="external nofollow noopener" target="_blank">link</a>. Hopefully, you find it helpful!!</p> <blockquote> <blockquote> <p>Until now error messages haven’t been more than mentioned, but if you have tried out the examples you have probably seen some. There are (at least) two distinguishable kinds of errors: syntax errors and exceptions.</p> </blockquote> </blockquote> <h2 id="1-syntax-errors">1. Syntax Errors</h2> <p>Syntax errors, also known as parsing errors, are perhaps the most common kind of complaint you get while you are still learning Python and any languages.</p> <div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">while</span> <span class="bp">True</span> <span class="nf">print</span><span class="p">(</span><span class="sh">'</span><span class="s">Hello world</span><span class="sh">'</span><span class="p">)</span>
  <span class="n">File</span> <span class="sh">"</span><span class="s">&lt;stdin&gt;</span><span class="sh">"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">1</span>
    <span class="k">while</span> <span class="bp">True</span> <span class="nf">print</span><span class="p">(</span><span class="sh">'</span><span class="s">Hello world</span><span class="sh">'</span><span class="p">)</span>
                   <span class="o">^</span>
<span class="nb">SyntaxError</span><span class="p">:</span> <span class="n">invalid</span> <span class="n">syntax</span>
</code></pre></div></div> <p>The parser repeats the offending line and displays a little ‘arrow’ pointing at the earliest point in the line where the error was detected. The error is caused by (or at least detected at) the token preceding the arrow: in the example, the error is detected at the function print(), since a colon (‘:’) is missing before it. File name and line number are printed so you know where to look in case the input came from a script.</p> <h2 id="2-exceptions">2. Exceptions</h2> <p>Even if a statement or expression is syntactically correct, it may cause an error when an attempt is made to execute it. Errors detected during execution are called exceptions and are not unconditionally fatal: you will soon learn how to handle them in Python programs. Most exceptions are not handled by programs, however, and result in error messages as shown here:</p> <div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="mi">10</span> <span class="o">*</span> <span class="p">(</span><span class="mi">1</span><span class="o">/</span><span class="mi">0</span><span class="p">)</span>
<span class="nc">Traceback </span><span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="n">File</span> <span class="sh">"</span><span class="s">&lt;stdin&gt;</span><span class="sh">"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">1</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
<span class="nb">ZeroDivisionError</span><span class="p">:</span> <span class="n">division</span> <span class="n">by</span> <span class="n">zero</span>

<span class="mi">4</span> <span class="o">+</span> <span class="n">spam</span><span class="o">*</span><span class="mi">3</span>
<span class="nc">Traceback </span><span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="n">File</span> <span class="sh">"</span><span class="s">&lt;stdin&gt;</span><span class="sh">"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">1</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
<span class="nb">NameError</span><span class="p">:</span> <span class="n">name</span> <span class="sh">'</span><span class="s">spam</span><span class="sh">'</span> <span class="ow">is</span> <span class="ow">not</span> <span class="n">defined</span>

<span class="sh">'</span><span class="s">2</span><span class="sh">'</span> <span class="o">+</span> <span class="mi">2</span>
<span class="nc">Traceback </span><span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="n">File</span> <span class="sh">"</span><span class="s">&lt;stdin&gt;</span><span class="sh">"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">1</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
<span class="nb">TypeError</span><span class="p">:</span> <span class="n">can</span> <span class="n">only</span> <span class="n">concatenate</span> <span class="nf">str </span><span class="p">(</span><span class="ow">not</span> <span class="sh">"</span><span class="s">int</span><span class="sh">"</span><span class="p">)</span> <span class="n">to</span> <span class="nb">str</span>
</code></pre></div></div> <p>The last line of the error message indicates what happened. Exceptions come in different types, and the type is printed as part of the message: the types in the example are <code class="language-plaintext highlighter-rouge">ZeroDivisionError</code>, <code class="language-plaintext highlighter-rouge">NameError</code> and <code class="language-plaintext highlighter-rouge">TypeError.</code> The string printed as the exception type is the name of the built-in exception that occurred. This is true for all built-in exceptions, but need not be true for user-defined exceptions (although it is a useful convention). Standard exception names are built-in identifiers (not reserved keywords).</p> <p>Built-in Exceptions lists the built-in exceptions and their meanings.</p> <h2 id="3-handling-exceptions">3. Handling Exceptions</h2> <p>It is possible to write programs that handle selected exceptions. Look at the following example, which asks the user for input until a valid integer has been entered, but allows the user to interrupt the program (using Control-C or whatever the operating system supports); note that a user-generated interruption is signalled by raising the KeyboardInterrupt exception.</p> <div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">while</span> <span class="bp">True</span><span class="p">:</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="n">x</span> <span class="o">=</span> <span class="nf">int</span><span class="p">(</span><span class="nf">input</span><span class="p">(</span><span class="sh">"</span><span class="s">Please enter a number: </span><span class="sh">"</span><span class="p">))</span>
        <span class="k">break</span>
    <span class="k">except</span> <span class="nb">ValueError</span><span class="p">:</span>
        <span class="nf">print</span><span class="p">(</span><span class="sh">"</span><span class="s">What a fool! Do you know what is a number? Do it again!</span><span class="sh">"</span><span class="p">)</span>
</code></pre></div></div> <p>The <code class="language-plaintext highlighter-rouge">try</code> statement works as follows.</p> <ul> <li>First, the try clause (the statement(s) between the try and except keywords) is executed.</li> <li>If no exception occurs, the except clause is skipped and execution of the try statement is finished.</li> <li>If an exception occurs during execution of the try clause, the rest of the clause is skipped. Then, if its type matches the exception named after the except keyword, the except clause is executed, and then execution continues after the try/except block.</li> <li>If an exception occurs which does not match the exception named in the except clause, it is passed on to outer try statements; if no handler is found, it is an unhandled exception and execution stops with a message as shown above.</li> </ul> <p>A <code class="language-plaintext highlighter-rouge">try</code> statement may have more than one except clause, to specify handlers for different exceptions. At most one handler will be executed. Handlers only handle exceptions that occur in the corresponding <code class="language-plaintext highlighter-rouge">try</code> clause, not in other handlers of the same try statement. An except clause may name multiple exceptions as a parenthesized tuple, for example:</p> <div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nf">except </span><span class="p">(</span><span class="nb">RuntimeError</span><span class="p">,</span> <span class="nb">TypeError</span><span class="p">,</span> <span class="nb">NameError</span><span class="p">):</span>
    <span class="k">pass</span>
</code></pre></div></div> <p>A class in an except clause is compatible with an exception if it is the same class or a base class thereof (but not the other way around — an except clause listing a derived class is not compatible with a base class). For example, the following code will print B, C, D in that order:</p> <div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">class</span> <span class="nc">B</span><span class="p">(</span><span class="nb">Exception</span><span class="p">):</span>
    <span class="k">pass</span>

<span class="k">class</span> <span class="nc">C</span><span class="p">(</span><span class="n">B</span><span class="p">):</span>
    <span class="k">pass</span>

<span class="k">class</span> <span class="nc">D</span><span class="p">(</span><span class="n">C</span><span class="p">):</span>
    <span class="k">pass</span>

<span class="k">for</span> <span class="n">cls</span> <span class="ow">in</span> <span class="p">[</span><span class="n">B</span><span class="p">,</span> <span class="n">C</span><span class="p">,</span> <span class="n">D</span><span class="p">]:</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="k">raise</span> <span class="nf">cls</span><span class="p">()</span>
    <span class="k">except</span> <span class="n">D</span><span class="p">:</span>
        <span class="nf">print</span><span class="p">(</span><span class="sh">"</span><span class="s">D</span><span class="sh">"</span><span class="p">)</span>
    <span class="k">except</span> <span class="n">C</span><span class="p">:</span>
        <span class="nf">print</span><span class="p">(</span><span class="sh">"</span><span class="s">C</span><span class="sh">"</span><span class="p">)</span>
    <span class="k">except</span> <span class="n">B</span><span class="p">:</span>
        <span class="nf">print</span><span class="p">(</span><span class="sh">"</span><span class="s">B</span><span class="sh">"</span><span class="p">)</span>
</code></pre></div></div> <p>Note that if the except clauses were reversed (with except B first), it would have printed B, B, B — the first matching except clause is triggered.</p> <p>When an exception occurs, it may have associated values, also known as the exception’s arguments. The presence and types of the arguments depend on the exception type.</p> <p>The except clause may specify a variable after the exception name. The variable is bound to the exception instance which typically has an args attribute that stores the arguments. For convenience, builtin exception types define <strong>str</strong>() to print all the arguments without explicitly accessing .args.</p> <div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">try</span><span class="p">:</span>
    <span class="k">raise</span> <span class="nc">Exception</span><span class="p">(</span><span class="sh">'</span><span class="s">spam</span><span class="sh">'</span><span class="p">,</span> <span class="sh">'</span><span class="s">eggs</span><span class="sh">'</span><span class="p">)</span>
<span class="k">except</span> <span class="nb">Exception</span> <span class="k">as</span> <span class="n">inst</span><span class="p">:</span>
    <span class="nf">print</span><span class="p">(</span><span class="nf">type</span><span class="p">(</span><span class="n">inst</span><span class="p">))</span>    <span class="c1"># the exception type
</span>    <span class="nf">print</span><span class="p">(</span><span class="n">inst</span><span class="p">.</span><span class="n">args</span><span class="p">)</span>     <span class="c1"># arguments stored in .args
</span>    <span class="nf">print</span><span class="p">(</span><span class="n">inst</span><span class="p">)</span>          <span class="c1"># __str__ allows args to be printed directly,
</span>                         <span class="c1"># but may be overridden in exception subclasses
</span>    <span class="n">x</span><span class="p">,</span> <span class="n">y</span> <span class="o">=</span> <span class="n">inst</span><span class="p">.</span><span class="n">args</span>     <span class="c1"># unpack args
</span>    <span class="nf">print</span><span class="p">(</span><span class="sh">'</span><span class="s">x =</span><span class="sh">'</span><span class="p">,</span> <span class="n">x</span><span class="p">)</span>
    <span class="nf">print</span><span class="p">(</span><span class="sh">'</span><span class="s">y =</span><span class="sh">'</span><span class="p">,</span> <span class="n">y</span><span class="p">)</span>
</code></pre></div></div> <p>The exception’s <strong>str</strong>() output is printed as the last part (‘detail’) of the message for unhandled exceptions.</p> <p><code class="language-plaintext highlighter-rouge">BaseException</code> is the common base class of all exceptions. One of its subclasses, <code class="language-plaintext highlighter-rouge">Exception</code>, is the base class of all the non-fatal exceptions. Exceptions which are not subclasses of <code class="language-plaintext highlighter-rouge">Exception</code> are not typically handled, because they are used to indicate that the program should terminate. They include <code class="language-plaintext highlighter-rouge">SystemExit</code> which is raised by <code class="language-plaintext highlighter-rouge">sys.exit()</code> and <code class="language-plaintext highlighter-rouge">KeyboardInterrupt</code> which is raised when a user wishes to interrupt the program.</p> <p><code class="language-plaintext highlighter-rouge">Exception</code> can be used as a wildcard that catches (almost) everything. However, it is good practice to be as specific as possible with the types of exceptions that we intend to handle, and to allow any unexpected exceptions to propagate on.</p> <p>The most common pattern for handling <code class="language-plaintext highlighter-rouge">Exception</code> is to print or log the exception and then re-raise it (allowing a caller to handle the exception as well):</p> <div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kn">import</span> <span class="n">sys</span>

<span class="k">try</span><span class="p">:</span>
    <span class="n">f</span> <span class="o">=</span> <span class="nf">open</span><span class="p">(</span><span class="sh">'</span><span class="s">myfile.txt</span><span class="sh">'</span><span class="p">)</span>
    <span class="n">s</span> <span class="o">=</span> <span class="n">f</span><span class="p">.</span><span class="nf">readline</span><span class="p">()</span>
    <span class="n">i</span> <span class="o">=</span> <span class="nf">int</span><span class="p">(</span><span class="n">s</span><span class="p">.</span><span class="nf">strip</span><span class="p">())</span>
<span class="k">except</span> <span class="nb">OSError</span> <span class="k">as</span> <span class="n">err</span><span class="p">:</span>
    <span class="nf">print</span><span class="p">(</span><span class="sh">'</span><span class="s">OSError: </span><span class="sh">'</span><span class="p">,</span> <span class="n">err</span><span class="p">)</span>
<span class="k">except</span> <span class="nb">ValueError</span><span class="p">:</span>
    <span class="nf">print</span><span class="p">(</span><span class="sh">'</span><span class="s">Could not convert data to an integer.</span><span class="sh">'</span><span class="p">)</span>
<span class="k">except</span> <span class="nb">Exception</span> <span class="k">as</span> <span class="n">err</span><span class="p">:</span>
    <span class="nf">print</span><span class="p">(</span><span class="sa">f</span><span class="sh">'</span><span class="s">Unexpected </span><span class="si">{</span><span class="n">err</span><span class="o">=</span><span class="si">}</span><span class="s">, </span><span class="si">{</span><span class="nf">type</span><span class="p">(</span><span class="n">err</span><span class="p">)</span><span class="o">=</span><span class="si">}</span><span class="sh">'</span><span class="p">)</span>
    <span class="k">raise</span>
</code></pre></div></div> <p>The <code class="language-plaintext highlighter-rouge">try</code> … <code class="language-plaintext highlighter-rouge">except</code> statement has an optional else clause, which, when present, must follow all except clauses. It is useful for code that must be executed if the try clause does not raise an exception. For example:</p> <div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">for</span> <span class="n">arg</span> <span class="ow">in</span> <span class="n">sys</span><span class="p">.</span><span class="n">argv</span><span class="p">[</span><span class="mi">1</span><span class="p">:]:</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="n">f</span> <span class="o">=</span> <span class="nf">open</span><span class="p">(</span><span class="n">arg</span><span class="p">,</span> <span class="sh">'</span><span class="s">r</span><span class="sh">'</span><span class="p">)</span>
    <span class="k">except</span> <span class="nb">OSError</span><span class="p">:</span>
        <span class="nf">print</span><span class="p">(</span><span class="sh">'</span><span class="s">cannot open</span><span class="sh">'</span><span class="p">,</span> <span class="n">arg</span><span class="p">)</span>
    <span class="k">else</span><span class="p">:</span>
        <span class="nf">print</span><span class="p">(</span><span class="n">arg</span><span class="p">,</span> <span class="sh">'</span><span class="s">has</span><span class="sh">'</span><span class="p">,</span> <span class="nf">len</span><span class="p">(</span><span class="n">f</span><span class="p">.</span><span class="nf">readlines</span><span class="p">()),</span> <span class="sh">'</span><span class="s">lines</span><span class="sh">'</span><span class="p">)</span>
        <span class="n">f</span><span class="p">.</span><span class="nf">close</span><span class="p">()</span>
</code></pre></div></div> <p>The use of the <code class="language-plaintext highlighter-rouge">else</code> clause is better than adding additional code to the try clause because it avoids accidentally catching an exception that wasn’t raised by the code being protected by the <code class="language-plaintext highlighter-rouge">try</code> … <code class="language-plaintext highlighter-rouge">except</code> statement.</p> <p>Exception handlers do not handle only exceptions that occur immediately in the try clause, but also those that occur inside functions that are called (even indirectly) in the try clause. For example:</p> <div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">def</span> <span class="nf">this_fails</span><span class="p">():</span>
    <span class="n">x</span> <span class="o">=</span> <span class="mi">1</span><span class="o">/</span><span class="mi">0</span>
<span class="k">try</span><span class="p">:</span>
    <span class="nf">this_fails</span><span class="p">()</span>
<span class="k">except</span> <span class="nb">ZeroDivisionError</span> <span class="k">as</span> <span class="n">err</span><span class="p">:</span>
    <span class="nf">print</span><span class="p">(</span><span class="sh">'</span><span class="s">Handling run-time error: </span><span class="sh">'</span><span class="p">,</span> <span class="n">err</span><span class="p">)</span>
</code></pre></div></div> <h2 id="4-raising-exceptions">4. Raising Exceptions</h2> <p>The raise statement allows the programmer to force a specified exception to occur. For example:</p> <div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">raise</span> <span class="nc">NameError</span><span class="p">(</span><span class="sh">'</span><span class="s">HiThere</span><span class="sh">'</span><span class="p">)</span>
<span class="nc">Traceback </span><span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="n">File</span> <span class="sh">"</span><span class="s">&lt;stdin&gt;</span><span class="sh">"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">1</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
<span class="nb">NameError</span><span class="p">:</span> <span class="n">HiThere</span>
</code></pre></div></div> <p>The sole argument to raise indicates the exception to be raised. This must be either an exception instance or an exception class (a class that derives from BaseException, such as Exception or one of its subclasses). If an exception class is passed, it will be implicitly instantiated by calling its constructor with no arguments:</p> <div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">raise</span> <span class="nb">ValueError</span>
</code></pre></div></div> <p>If you need to determine whether an exception was raised but don’t intend to handle it, a simpler form of the raise statement allows you to re-reaise the exception:</p> <div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">try</span><span class="p">:</span>
    <span class="k">raise</span> <span class="nc">NameError</span><span class="p">(</span><span class="sh">'</span><span class="s">HiThere</span><span class="sh">'</span><span class="p">)</span>
<span class="k">except</span> <span class="nb">NameError</span><span class="p">:</span>
    <span class="nf">print</span><span class="p">(</span><span class="sh">'</span><span class="s">An exception flew by!</span><span class="sh">'</span><span class="p">)</span>
    <span class="k">raise</span>
</code></pre></div></div> <h2 id="5-exception-chaining">5. Exception Chaining</h2> <p>If an unhandled exception occurs inside an except section, it will have the exception being handled attached to it and included in the error message:</p> <div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">try</span><span class="p">:</span>
    <span class="nf">open</span><span class="p">(</span><span class="sh">"</span><span class="s">database.sqlite</span><span class="sh">"</span><span class="p">)</span>
<span class="k">except</span> <span class="nb">OSError</span><span class="p">:</span>
    <span class="k">raise</span> <span class="nc">RuntimeError</span><span class="p">(</span><span class="sh">"</span><span class="s">unable to handle error</span><span class="sh">"</span><span class="p">)</span>

<span class="nc">Traceback </span><span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="n">File</span> <span class="sh">"</span><span class="s">&lt;stdin&gt;</span><span class="sh">"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">2</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
<span class="nb">FileNotFoundError</span><span class="p">:</span> <span class="p">[</span><span class="n">Errno</span> <span class="mi">2</span><span class="p">]</span> <span class="n">No</span> <span class="n">such</span> <span class="nb">file</span> <span class="ow">or</span> <span class="n">directory</span><span class="p">:</span> <span class="sh">'</span><span class="s">database.sqlite</span><span class="sh">'</span>

<span class="n">During</span> <span class="n">handling</span> <span class="n">of</span> <span class="n">the</span> <span class="n">above</span> <span class="n">exception</span><span class="p">,</span> <span class="n">another</span> <span class="n">exception</span> <span class="n">occurred</span><span class="p">:</span>

<span class="nc">Traceback </span><span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="n">File</span> <span class="sh">"</span><span class="s">&lt;stdin&gt;</span><span class="sh">"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">4</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
<span class="nb">RuntimeError</span><span class="p">:</span> <span class="n">unable</span> <span class="n">to</span> <span class="n">handle</span> <span class="n">error</span>
</code></pre></div></div> <p>To indicate that an exception is a direct consequence of another, the raise statement allows an optional from clause:</p> <div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">raise</span> <span class="nb">RuntimeError</span> <span class="k">from</span> <span class="n">exc</span>
</code></pre></div></div> <p>This can be useful when you are transforming exceptions. For example:</p> <div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">def</span> <span class="nf">func</span><span class="p">():</span>
    <span class="k">raise</span> <span class="nb">ConnectionError</span>
<span class="k">try</span><span class="p">:</span>
    <span class="nf">func</span><span class="p">()</span>
<span class="k">except</span> <span class="n">Connection</span> <span class="k">as</span> <span class="n">exc</span><span class="p">:</span>
    <span class="k">raise</span> <span class="nc">RuntimeError</span><span class="p">(</span><span class="sh">'</span><span class="s">Fail to open database</span><span class="sh">'</span><span class="p">)</span> <span class="k">from</span> <span class="n">exc</span>

<span class="nc">Traceback </span><span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="n">File</span> <span class="sh">"</span><span class="s">&lt;stdin&gt;</span><span class="sh">"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">2</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
  <span class="n">File</span> <span class="sh">"</span><span class="s">&lt;stdin&gt;</span><span class="sh">"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">2</span><span class="p">,</span> <span class="ow">in</span> <span class="n">func</span>
<span class="nb">ConnectionError</span>

<span class="n">The</span> <span class="n">above</span> <span class="n">exception</span> <span class="n">was</span> <span class="n">the</span> <span class="n">direct</span> <span class="n">cause</span> <span class="n">of</span> <span class="n">the</span> <span class="n">following</span> <span class="n">exception</span><span class="p">:</span>

<span class="nc">Traceback </span><span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="n">File</span> <span class="sh">"</span><span class="s">&lt;stdin&gt;</span><span class="sh">"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">4</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
<span class="nb">RuntimeError</span><span class="p">:</span> <span class="n">Failed</span> <span class="n">to</span> <span class="nb">open</span> <span class="n">database</span>
</code></pre></div></div> <p>It allows disabling automatic exception chaining using the from None idiom:</p> <div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">try</span><span class="p">:</span>
    <span class="nf">open</span><span class="p">(</span><span class="sh">'</span><span class="s">database.sqlite</span><span class="sh">'</span><span class="p">)</span>
<span class="k">except</span> <span class="nb">OSError</span><span class="p">:</span>
    <span class="k">raise</span> <span class="nb">RuntimeError</span> <span class="k">from</span> <span class="bp">None</span>

<span class="nc">Traceback </span><span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="n">File</span> <span class="sh">"</span><span class="s">&lt;stdin&gt;</span><span class="sh">"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">4</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
<span class="nb">RuntimeError</span>
</code></pre></div></div> <h2 id="6-user-defined-exceptions">6. User-defined Exceptions</h2> <p>Programs may name their own exceptions by creating a new exception class (see Classes for more about Python classes). Exceptions should typically be derived from the Exception class, either directly or indirectly.</p> <p>Exception classes can be defined which do anything any other class can do, but are usually kept simple, often only offering a number of attributes that allow information about the error to be extracted by handlers for the exception.</p> <p>Most exceptions are defined with names that end in “Error”, similar to the naming of the standard exceptions.</p> <p>Many standard modules define their own exceptions to report errors that may occur in functions they define.</p> <div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">class</span> <span class="nc">InvalidInputError</span><span class="p">(</span><span class="nb">Exception</span><span class="p">):</span>
    <span class="k">def</span> <span class="nf">__init__</span><span class="p">(</span><span class="n">self</span><span class="p">,</span> <span class="n">message</span><span class="p">):</span>
        <span class="nf">super</span><span class="p">().</span><span class="nf">__init__</span><span class="p">(</span><span class="n">message</span><span class="p">)</span>
        <span class="n">self</span><span class="p">.</span><span class="n">message</span> <span class="o">=</span> <span class="n">message</span>

<span class="k">def</span> <span class="nf">process_input</span><span class="p">(</span><span class="n">value</span><span class="p">):</span>
    <span class="k">if</span> <span class="ow">not</span> <span class="nf">isinstance</span><span class="p">(</span><span class="n">value</span><span class="p">,</span> <span class="nb">int</span><span class="p">):</span>
        <span class="k">raise</span> <span class="nc">InvalidInputError</span><span class="p">(</span><span class="sh">"</span><span class="s">Invalid input! Expected an integer.</span><span class="sh">"</span><span class="p">)</span>

    <span class="c1"># Process the input value here...
</span>
<span class="c1"># Example usage
</span><span class="k">try</span><span class="p">:</span>
    <span class="n">user_input</span> <span class="o">=</span> <span class="nf">input</span><span class="p">(</span><span class="sh">"</span><span class="s">Enter an integer: </span><span class="sh">"</span><span class="p">)</span>
    <span class="nf">process_input</span><span class="p">(</span><span class="n">user_input</span><span class="p">)</span>
<span class="k">except</span> <span class="n">InvalidInputError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="nf">print</span><span class="p">(</span><span class="sh">"</span><span class="s">Error:</span><span class="sh">"</span><span class="p">,</span> <span class="n">e</span><span class="p">.</span><span class="n">message</span><span class="p">)</span>
</code></pre></div></div> <h2 id="7-defining-clean-up-actions">7. Defining Clean-up Actions</h2> <p>The <code class="language-plaintext highlighter-rouge">try</code> statement has another optional clause which is intended to define clean-up actions that must be executed under all circumstances. For example:</p> <div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">try</span><span class="p">:</span>
    <span class="k">raise</span> <span class="nb">KeyboardInterrupt</span>
<span class="k">finally</span><span class="p">:</span>
    <span class="nf">print</span><span class="p">(</span><span class="sh">'</span><span class="s">Let</span><span class="sh">''</span><span class="s">s drink beer!</span><span class="sh">'</span><span class="p">)</span>
</code></pre></div></div> <p>If a <code class="language-plaintext highlighter-rouge">finally</code> clause is present, the <code class="language-plaintext highlighter-rouge">finally</code> clause will execute as the last task before the <code class="language-plaintext highlighter-rouge">try</code> statement completes. The finally clause runs whether or not the try statement produces an exception. The following points discuss more complex cases when an exception occurs:</p> <ul> <li>If an exception occurs during execution of the <code class="language-plaintext highlighter-rouge">try</code> clause, the exception may be handled by an except clause. If the exception is not handled by an except clause, the exception is re-raised <strong>after</strong> the <code class="language-plaintext highlighter-rouge">finally</code> clause has been executed.</li> <li>An exception could occur during execution of an <code class="language-plaintext highlighter-rouge">except</code> or <code class="language-plaintext highlighter-rouge">else</code> clause. Again, the exception is re-raised <strong>after</strong> the <code class="language-plaintext highlighter-rouge">finally</code> clause has been executed.</li> <li>If the <code class="language-plaintext highlighter-rouge">finally</code> clause executes a <code class="language-plaintext highlighter-rouge">break</code>, continue or return statement, <strong>exceptions are not re-raised</strong>.</li> <li>If the <code class="language-plaintext highlighter-rouge">try</code> statement reaches a <code class="language-plaintext highlighter-rouge">break</code>, continue or return statement, the finally clause will <code class="language-plaintext highlighter-rouge">execute</code> just <strong>prior to the break</strong>, continue or return statement’s execution.</li> <li>If a <code class="language-plaintext highlighter-rouge">finally</code> clause includes a <code class="language-plaintext highlighter-rouge">return</code> statement, <strong>the returned value will be the one from the finally clause’s return statement, not the value from the try clause’s return statement.</strong> </li> </ul> <p>For example:</p> <div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">def</span> <span class="nf">bool_return</span><span class="p">():</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="k">return</span> <span class="bp">True</span>
    <span class="k">finally</span><span class="p">:</span>
        <span class="k">return</span> <span class="bp">False</span>

<span class="nf">bool_return</span><span class="p">()</span>

<span class="c1"># False
</span></code></pre></div></div> <p>A more complicated example:</p> <div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">def</span> <span class="nf">divide</span><span class="p">(</span><span class="n">x</span><span class="p">,</span> <span class="n">y</span><span class="p">):</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="n">result</span> <span class="o">=</span> <span class="n">x</span> <span class="o">/</span> <span class="n">y</span>
    <span class="k">except</span> <span class="nb">ZeroDivisionError</span><span class="p">:</span>
        <span class="nf">print</span><span class="p">(</span><span class="sh">"</span><span class="s">division by zero!</span><span class="sh">"</span><span class="p">)</span>
    <span class="k">else</span><span class="p">:</span>
        <span class="nf">print</span><span class="p">(</span><span class="sh">"</span><span class="s">result is</span><span class="sh">"</span><span class="p">,</span> <span class="n">result</span><span class="p">)</span>
    <span class="k">finally</span><span class="p">:</span>
        <span class="nf">print</span><span class="p">(</span><span class="sh">"</span><span class="s">executing finally clause</span><span class="sh">"</span><span class="p">)</span>

<span class="nf">divide</span><span class="p">(</span><span class="mi">2</span><span class="p">,</span> <span class="mi">1</span><span class="p">)</span>
<span class="n">result</span> <span class="ow">is</span> <span class="mf">2.0</span>
<span class="n">executing</span> <span class="k">finally</span> <span class="n">clause</span>
<span class="nf">divide</span><span class="p">(</span><span class="mi">2</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>
<span class="n">division</span> <span class="n">by</span> <span class="n">zero</span><span class="err">!</span>
<span class="n">executing</span> <span class="k">finally</span> <span class="n">clause</span>
<span class="nf">divide</span><span class="p">(</span><span class="sh">"</span><span class="s">2</span><span class="sh">"</span><span class="p">,</span> <span class="sh">"</span><span class="s">1</span><span class="sh">"</span><span class="p">)</span>
<span class="n">executing</span> <span class="k">finally</span> <span class="n">clause</span>
<span class="nc">Traceback </span><span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="n">File</span> <span class="sh">"</span><span class="s">&lt;stdin&gt;</span><span class="sh">"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">1</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
  <span class="n">File</span> <span class="sh">"</span><span class="s">&lt;stdin&gt;</span><span class="sh">"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">3</span><span class="p">,</span> <span class="ow">in</span> <span class="n">divide</span>
<span class="nb">TypeError</span><span class="p">:</span> <span class="n">unsupported</span> <span class="n">operand</span> <span class="nf">type</span><span class="p">(</span><span class="n">s</span><span class="p">)</span> <span class="k">for</span> <span class="o">/</span><span class="p">:</span> <span class="sh">'</span><span class="s">str</span><span class="sh">'</span> <span class="ow">and</span> <span class="sh">'</span><span class="s">str</span><span class="sh">'</span>
</code></pre></div></div> <h2 id="8-predefined-clean-up-actions">8. Predefined Clean-up Actions</h2> <p>Some objects define standard clean-up actions to be undertaken when the object is no longer needed, regardless of whether or not the operation using the object succeeded or failed. Look at the following example, which tries to open a file and print its contents to the screen.</p> <div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">for</span> <span class="n">line</span> <span class="ow">in</span> <span class="nf">open</span><span class="p">(</span><span class="sh">"</span><span class="s">myfile.txt</span><span class="sh">"</span><span class="p">):</span>
    <span class="nf">print</span><span class="p">(</span><span class="n">line</span><span class="p">,</span> <span class="n">end</span><span class="o">=</span><span class="sh">""</span><span class="p">)</span>
</code></pre></div></div> <p>The problem with this code is that it leaves the file open for an indeterminate amount of time after this part of the code has finished executing. This is not an issue in simple scripts, but can be a problem for larger applications. The with statement allows objects like files to be used in a way that ensures they are always cleaned up promptly and correctly.</p> <div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">with</span> <span class="nf">open</span><span class="p">(</span><span class="sh">"</span><span class="s">myfile.txt</span><span class="sh">"</span><span class="p">)</span> <span class="k">as</span> <span class="n">f</span><span class="p">:</span>
    <span class="k">for</span> <span class="n">line</span> <span class="ow">in</span> <span class="n">f</span><span class="p">:</span>
        <span class="nf">print</span><span class="p">(</span><span class="n">line</span><span class="p">,</span> <span class="n">end</span><span class="o">=</span><span class="sh">""</span><span class="p">)</span>
</code></pre></div></div> <p>After the statement is executed, the file f is always closed, even if a problem was encountered while processing the lines. Objects which, like files, provide predefined clean-up actions will indicate this in their documentation.</p> <h2 id="9-raising-and-handling-multiple-unrelated-exceptions">9. Raising and Handling Multiple Unrelated Exceptions</h2> <p>There are situations where it is necessary to report several exceptions that have occurred. This is often the case in concurrency frameworks, when several tasks may have failed in parallel, but there are also other use cases where it is desirable to continue execution and collect multiple errors rather than raise the first exception.</p> <p>The builtin ExceptionGroup wraps a list of exception instances so that they can be raised together. It is an exception itself, so it can be caught like any other exception.</p> <div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">def</span> <span class="nf">f</span><span class="p">():</span>
    <span class="n">excs</span> <span class="o">=</span> <span class="p">[</span><span class="nc">OSError</span><span class="p">(</span><span class="sh">'</span><span class="s">error 1</span><span class="sh">'</span><span class="p">),</span> <span class="nc">SystemError</span><span class="p">(</span><span class="sh">'</span><span class="s">error 2</span><span class="sh">'</span><span class="p">)]</span>
    <span class="k">raise</span> <span class="nc">ExceptionGroup</span><span class="p">(</span><span class="sh">'</span><span class="s">there were problems</span><span class="sh">'</span><span class="p">,</span> <span class="n">excs</span><span class="p">)</span>

<span class="nf">f</span><span class="p">()</span>

  <span class="o">+</span> <span class="nb">Exception</span> <span class="n">Group</span> <span class="nc">Traceback </span><span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="o">|</span>   <span class="n">File</span> <span class="sh">"</span><span class="s">&lt;stdin&gt;</span><span class="sh">"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">1</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
  <span class="o">|</span>   <span class="n">File</span> <span class="sh">"</span><span class="s">&lt;stdin&gt;</span><span class="sh">"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">3</span><span class="p">,</span> <span class="ow">in</span> <span class="n">f</span>
  <span class="o">|</span> <span class="n">ExceptionGroup</span><span class="p">:</span> <span class="n">there</span> <span class="n">were</span> <span class="n">problems</span>
  <span class="o">+-+----------------</span> <span class="mi">1</span> <span class="o">----------------</span>
    <span class="o">|</span> <span class="nb">OSError</span><span class="p">:</span> <span class="n">error</span> <span class="mi">1</span>
    <span class="o">+----------------</span> <span class="mi">2</span> <span class="o">----------------</span>
    <span class="o">|</span> <span class="nb">SystemError</span><span class="p">:</span> <span class="n">error</span> <span class="mi">2</span>
    <span class="o">+------------------------------------</span>
<span class="k">try</span><span class="p">:</span>
    <span class="nf">f</span><span class="p">()</span>
<span class="k">except</span> <span class="nb">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="nf">print</span><span class="p">(</span><span class="sa">f</span><span class="sh">'</span><span class="s">caught </span><span class="si">{</span><span class="nf">type</span><span class="p">(</span><span class="n">e</span><span class="p">)</span><span class="si">}</span><span class="s">: e</span><span class="sh">'</span><span class="p">)</span>

<span class="n">caught</span> <span class="o">&lt;</span><span class="k">class</span> <span class="err">'</span><span class="nc">ExceptionGroup</span><span class="sh">'</span><span class="s">&gt;: e
</span></code></pre></div></div> <p>By using <code class="language-plaintext highlighter-rouge">except*</code> instead of <code class="language-plaintext highlighter-rouge">except</code>, we can selectively handle only the exceptions in the group that match a certain type. In the following example, which shows a nested exception group, each except* clause extracts from the group exceptions of a certain type while letting all other exceptions propagate to other clauses and eventually to be reraised.</p> <div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">def</span> <span class="nf">f</span><span class="p">():</span>
    <span class="k">raise</span> <span class="nc">ExceptionGroup</span><span class="p">(</span><span class="sh">"</span><span class="s">group1</span><span class="sh">"</span><span class="p">,</span>
                         <span class="p">[</span><span class="nc">OSError</span><span class="p">(</span><span class="mi">1</span><span class="p">),</span>
                          <span class="nc">SystemError</span><span class="p">(</span><span class="mi">2</span><span class="p">),</span>
                          <span class="nc">ExceptionGroup</span><span class="p">(</span><span class="sh">"</span><span class="s">group2</span><span class="sh">"</span><span class="p">,</span>
                                         <span class="p">[</span><span class="nc">OSError</span><span class="p">(</span><span class="mi">3</span><span class="p">),</span> <span class="nc">RecursionError</span><span class="p">(</span><span class="mi">4</span><span class="p">)])])</span>

<span class="k">try</span><span class="p">:</span>
    <span class="nf">f</span><span class="p">()</span>
<span class="k">except</span><span class="o">*</span> <span class="nb">OSError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="nf">print</span><span class="p">(</span><span class="sh">"</span><span class="s">There were OSErrors</span><span class="sh">"</span><span class="p">)</span>
<span class="k">except</span><span class="o">*</span> <span class="nb">SystemError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="nf">print</span><span class="p">(</span><span class="sh">"</span><span class="s">There were SystemErrors</span><span class="sh">"</span><span class="p">)</span>

<span class="n">There</span> <span class="n">were</span> <span class="n">OSErrors</span>
<span class="n">There</span> <span class="n">were</span> <span class="n">SystemErrors</span>
  <span class="o">+</span> <span class="nb">Exception</span> <span class="n">Group</span> <span class="nc">Traceback </span><span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="o">|</span>   <span class="n">File</span> <span class="sh">"</span><span class="s">&lt;stdin&gt;</span><span class="sh">"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">2</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
  <span class="o">|</span>   <span class="n">File</span> <span class="sh">"</span><span class="s">&lt;stdin&gt;</span><span class="sh">"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">2</span><span class="p">,</span> <span class="ow">in</span> <span class="n">f</span>
  <span class="o">|</span> <span class="n">ExceptionGroup</span><span class="p">:</span> <span class="n">group1</span>
  <span class="o">+-+----------------</span> <span class="mi">1</span> <span class="o">----------------</span>
    <span class="o">|</span> <span class="n">ExceptionGroup</span><span class="p">:</span> <span class="n">group2</span>
    <span class="o">+-+----------------</span> <span class="mi">1</span> <span class="o">----------------</span>
      <span class="o">|</span> <span class="nb">RecursionError</span><span class="p">:</span> <span class="mi">4</span>
      <span class="o">+-------------</span>
</code></pre></div></div> <p>Note that the exceptions nested in an exception group must be instances, not types. This is because in practice the exceptions would typically be ones that have already been raised and caught by the program, along the following pattern:</p> <div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">excs</span> <span class="o">=</span> <span class="p">[]</span>
<span class="k">for</span> <span class="n">test</span> <span class="ow">in</span> <span class="n">tests</span><span class="p">:</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="n">test</span><span class="p">.</span><span class="nf">run</span><span class="p">()</span>
    <span class="k">except</span> <span class="nb">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
        <span class="n">excs</span><span class="p">.</span><span class="nf">append</span><span class="p">(</span><span class="n">e</span><span class="p">)</span>

<span class="k">if</span> <span class="n">excs</span><span class="p">:</span>
   <span class="k">raise</span> <span class="nc">ExceptionGroup</span><span class="p">(</span><span class="sh">"</span><span class="s">Test Failures</span><span class="sh">"</span><span class="p">,</span> <span class="n">excs</span><span class="p">)</span>
</code></pre></div></div> <h2 id="10-enriching-exceptions-with-notes">10. Enriching Exceptions with Notes</h2> <p>When an exception is created in order to be raised, it is usually initialized with information that describes the error that has occurred. There are cases where it is useful to add information after the exception was caught. For this purpose, exceptions have a method add_note(note) that accepts a string and adds it to the exception’s notes list. The standard traceback rendering includes all notes, in the order they were added, after the exception.</p> <div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">try</span><span class="p">:</span>
    <span class="k">raise</span> <span class="nc">TypeError</span><span class="p">(</span><span class="sh">'</span><span class="s">bad type</span><span class="sh">'</span><span class="p">)</span>
<span class="k">except</span> <span class="nb">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="n">e</span><span class="p">.</span><span class="nf">add_note</span><span class="p">(</span><span class="sh">'</span><span class="s">Add some information</span><span class="sh">'</span><span class="p">)</span>
    <span class="n">e</span><span class="p">.</span><span class="nf">add_note</span><span class="p">(</span><span class="sh">'</span><span class="s">Add some more information</span><span class="sh">'</span><span class="p">)</span>
    <span class="k">raise</span>

<span class="nc">Traceback </span><span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="n">File</span> <span class="sh">"</span><span class="s">&lt;stdin&gt;</span><span class="sh">"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">2</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
<span class="nb">TypeError</span><span class="p">:</span> <span class="n">bad</span> <span class="nb">type</span>
<span class="n">Add</span> <span class="n">some</span> <span class="n">information</span>
<span class="n">Add</span> <span class="n">some</span> <span class="n">more</span> <span class="n">information</span>
</code></pre></div></div> <p>For example, when collecting exceptions into an exception group, we may want to add context information for the individual errors. In the following each exception in the group has a note indicating when this error has occurred.</p> <div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">def</span> <span class="nf">f</span><span class="p">():</span>
    <span class="k">raise</span> <span class="nc">OSError</span><span class="p">(</span><span class="sh">'</span><span class="s">operation failed</span><span class="sh">'</span><span class="p">)</span>

<span class="n">excs</span> <span class="o">=</span> <span class="p">[]</span>
<span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nf">range</span><span class="p">(</span><span class="mi">3</span><span class="p">):</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="nf">f</span><span class="p">()</span>
    <span class="k">except</span> <span class="nb">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
        <span class="n">e</span><span class="p">.</span><span class="nf">add_note</span><span class="p">(</span><span class="sa">f</span><span class="sh">'</span><span class="s">Happened in Iteration </span><span class="si">{</span><span class="n">i</span><span class="o">+</span><span class="mi">1</span><span class="si">}</span><span class="sh">'</span><span class="p">)</span>
        <span class="n">excs</span><span class="p">.</span><span class="nf">append</span><span class="p">(</span><span class="n">e</span><span class="p">)</span>

<span class="k">raise</span> <span class="nc">ExceptionGroup</span><span class="p">(</span><span class="sh">'</span><span class="s">We have some problems</span><span class="sh">'</span><span class="p">,</span> <span class="n">excs</span><span class="p">)</span>
  <span class="o">+</span> <span class="nb">Exception</span> <span class="n">Group</span> <span class="nc">Traceback </span><span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="o">|</span>   <span class="n">File</span> <span class="sh">"</span><span class="s">&lt;stdin&gt;</span><span class="sh">"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">1</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
  <span class="o">|</span> <span class="n">ExceptionGroup</span><span class="p">:</span> <span class="n">We</span> <span class="n">have</span> <span class="n">some</span> <span class="nf">problems </span><span class="p">(</span><span class="mi">3</span> <span class="n">sub</span><span class="o">-</span><span class="n">exceptions</span><span class="p">)</span>
  <span class="o">+-+----------------</span> <span class="mi">1</span> <span class="o">----------------</span>
    <span class="o">|</span> <span class="nc">Traceback </span><span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
    <span class="o">|</span>   <span class="n">File</span> <span class="sh">"</span><span class="s">&lt;stdin&gt;</span><span class="sh">"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">3</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
    <span class="o">|</span>   <span class="n">File</span> <span class="sh">"</span><span class="s">&lt;stdin&gt;</span><span class="sh">"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">2</span><span class="p">,</span> <span class="ow">in</span> <span class="n">f</span>
    <span class="o">|</span> <span class="nb">OSError</span><span class="p">:</span> <span class="n">operation</span> <span class="n">failed</span>
    <span class="o">|</span> <span class="n">Happened</span> <span class="ow">in</span> <span class="n">Iteration</span> <span class="mi">1</span>
    <span class="o">+----------------</span> <span class="mi">2</span> <span class="o">----------------</span>
    <span class="o">|</span> <span class="nc">Traceback </span><span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
    <span class="o">|</span>   <span class="n">File</span> <span class="sh">"</span><span class="s">&lt;stdin&gt;</span><span class="sh">"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">3</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
    <span class="o">|</span>   <span class="n">File</span> <span class="sh">"</span><span class="s">&lt;stdin&gt;</span><span class="sh">"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">2</span><span class="p">,</span> <span class="ow">in</span> <span class="n">f</span>
    <span class="o">|</span> <span class="nb">OSError</span><span class="p">:</span> <span class="n">operation</span> <span class="n">failed</span>
    <span class="o">|</span> <span class="n">Happened</span> <span class="ow">in</span> <span class="n">Iteration</span> <span class="mi">2</span>
    <span class="o">+----------------</span> <span class="mi">3</span> <span class="o">----------------</span>
    <span class="o">|</span> <span class="nc">Traceback </span><span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
    <span class="o">|</span>   <span class="n">File</span> <span class="sh">"</span><span class="s">&lt;stdin&gt;</span><span class="sh">"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">3</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
    <span class="o">|</span>   <span class="n">File</span> <span class="sh">"</span><span class="s">&lt;stdin&gt;</span><span class="sh">"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">2</span><span class="p">,</span> <span class="ow">in</span> <span class="n">f</span>
    <span class="o">|</span> <span class="nb">OSError</span><span class="p">:</span> <span class="n">operation</span> <span class="n">failed</span>
    <span class="o">|</span> <span class="n">Happened</span> <span class="ow">in</span> <span class="n">Iteration</span> <span class="mi">3</span>
    <span class="o">+------------------------------------</span>
</code></pre></div></div> </div> </article> <br> <hr> <br> <ul class="list-disc pl-8"></ul> <h2 class="text-3xl font-semibold mb-4 mt-12">Enjoy Reading This Article?</h2> <p class="mb-2">Here are some more articles you might like to read next:</p> <li class="my-2"> <a class="text-pink-700 underline font-semibold hover:text-pink-800" href="/myblog/2023/build-ds-project/">Get lost when trying to build a Data Science Project</a> </li> <li class="my-2"> <a class="text-pink-700 underline font-semibold hover:text-pink-800" href="/myblog/2023/python_file_handling/">Handling File in Python</a> </li> <li class="my-2"> <a class="text-pink-700 underline font-semibold hover:text-pink-800" href="/myblog/2023/intro_pytorch/">Introduction to PyTorch</a> </li> <li class="my-2"> <a class="text-pink-700 underline font-semibold hover:text-pink-800" href="/myblog/2023/review-machine-learning/">Basic Concepts of Machine Learning</a> </li> <li class="my-2"> <a class="text-pink-700 underline font-semibold hover:text-pink-800" href="/myblog/2023/performance-measures/">Performance Metrics in Machine Learning</a> </li> </div> </div> <footer class="fixed-bottom"> <div class="container mt-0"> © Copyright 2024 Duc Minh Quang Nguyen. # Powered by <a href="https://jekyllrb.com/" target="_blank" rel="external nofollow noopener">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio" rel="external nofollow noopener" target="_blank">al-folio</a> theme. # Hosted by <a href="https://pages.github.com/" target="_blank" rel="external nofollow noopener">GitHub Pages</a>. # Photos from <a href="https://unsplash.com" target="_blank" rel="external nofollow noopener">Unsplash</a>. </div> </footer> <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script> <script src="/assets/js/bootstrap.bundle.min.js"></script> <script src="https://cdn.jsdelivr.net/npm/mdbootstrap@4.20.0/js/mdb.min.js" integrity="sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA=" crossorigin="anonymous"></script> <script defer src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI=" crossorigin="anonymous"></script> <script defer src="https://cdn.jsdelivr.net/npm/imagesloaded@4/imagesloaded.pkgd.min.js"></script> <script defer src="/assets/js/masonry.js" type="text/javascript"></script> <script defer src="https://cdn.jsdelivr.net/npm/medium-zoom@1.0.8/dist/medium-zoom.min.js" integrity="sha256-7PhEpEWEW0XXQ0k6kQrPKwuoIomz8R8IYyuU1Qew4P8=" crossorigin="anonymous"></script> <script defer src="/assets/js/zoom.js?7b30caa5023af4af8408a472dc4e1ebb"></script> <script defer src="https://unpkg.com/bootstrap-table@1.22.1/dist/bootstrap-table.min.js"></script> <script src="/assets/js/no_defer.js?d633890033921b33e0ceb13d22340a9c"></script> <script defer src="/assets/js/common.js?acdb9690d7641b2f8d40529018c71a01"></script> <script defer src="/assets/js/copy_code.js?07b8786bab9b4abe90d10e61f7d12ff7" type="text/javascript"></script> <script async src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script> <script async src="https://badge.dimensions.ai/badge.js"></script> <script type="text/javascript">window.MathJax={tex:{tags:"ams"}};</script> <script defer type="text/javascript" id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3.2.0/es5/tex-mml-chtml.js"></script> <script defer src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script> <script type="text/javascript">function progressBarSetup(){"max"in document.createElement("progress")?(initializeProgressElement(),$(document).on("scroll",function(){progressBar.attr({value:getCurrentScrollPosition()})}),$(window).on("resize",initializeProgressElement)):(resizeProgressBar(),$(document).on("scroll",resizeProgressBar),$(window).on("resize",resizeProgressBar))}function getCurrentScrollPosition(){return $(window).scrollTop()}function initializeProgressElement(){let e=$("#navbar").outerHeight(!0);$("body").css({"padding-top":e}),$("progress-container").css({"padding-top":e}),progressBar.css({top:e}),progressBar.attr({max:getDistanceToScroll(),value:getCurrentScrollPosition()})}function getDistanceToScroll(){return $(document).height()-$(window).height()}function resizeProgressBar(){progressBar.css({width:getWidthPercentage()+"%"})}function getWidthPercentage(){return getCurrentScrollPosition()/getDistanceToScroll()*100}const progressBar=$("#progress");window.onload=function(){setTimeout(progressBarSetup,50)};</script> </body> </html>